### ISSUE TITLE
properties xmx and xms have no effect unless jvm_opts is defined

### ISSUE THREAD

**Issue by DBarthe** [robertdebock/ansible-role-tomcat#17]
Hello and thanks for this role.

Just noticed that properties xmx and xms have no effect unless jvm_opts is defined.

**Comment by robertdebock** [comment]
Hi, thanks for your feedback, I'll try to reproduce this and write a fix.

**Comment by robertdebock** [comment]
Cool, thanks! I'll let CI test and merge when successfully completed.
