### ISSUE TITLE
Configurable listening IP address

### ISSUE THREAD

**Issue by FuhuXia** [robertdebock/ansible-role-tomcat#19]
## Proposed feature

Add `connector_address` so user can configure which IP address the server is listening to.

## Rationale

We have Nginx built on top of Tomcat, `127.0.0.1` is what we really need instead of the default `0.0.0.0`.

**Comment by robertdebock** [comment]
That looks like a very valid feature.

I'll work on the test to reproduce and a fix.

Thanks!

**Comment by robertdebock** [comment]
I've just releases 4.5.0, can you see if that makes sense to you? If not (or if you have questions) don't hesitate to re-open this issue!

Once more, thanks for your feedback!

**Comment by FuhuXia** [comment]
Great. Tried 4.5.0 and the feature is working. Good work indeed.
